export type Pairing = Readonly<{ port: number; secret: string }>;
export const DEFAULT_COMPANION_PORT = 24817;
export const PAIRING_ENV = "LSEW_AGENT_CONNECTION";
export const PAIRING_LIFETIME_MS = 120000;

export function parsePairingCode(code: string): Pairing {
  const match = /^wb1:([1-9]\d{3,4}):([a-f0-9]{64})$/.exec(code.trim());
  const port = Number(match?.[1]);
  if (!match || port < 1024 || port > 65535) throw new Error("Invalid companion connection credential. Use the MCP configuration generated by setup.");
  return { port, secret: match[2]! };
}

export function randomNonce(): string {
  return Array.from(crypto.getRandomValues(new Uint8Array(32)), byte => byte.toString(16).padStart(2, "0")).join("");
}

export function proofText(side: "client" | "server", role: "agent" | "panel", clientNonce: string, serverNonce: string): string {
  return `lightstreamer-workbench-pairing-v1\n${side}\n${role}\n${clientNonce}\n${serverNonce}`;
}

async function key(secret: string) {
  return crypto.subtle.importKey("raw", new TextEncoder().encode(secret), { name: "HMAC", hash: "SHA-256" }, false, ["sign", "verify"]);
}
export async function pairingProof(secret: string, text: string): Promise<string> {
  const signature = await crypto.subtle.sign("HMAC", await key(secret), new TextEncoder().encode(text));
  return Array.from(new Uint8Array(signature), byte => byte.toString(16).padStart(2, "0")).join("");
}
export async function verifyPairingProof(secret: string, text: string, proof: unknown): Promise<boolean> {
  if (typeof proof !== "string" || !/^[a-f0-9]{64}$/.test(proof)) return false;
  const bytes = Uint8Array.from(proof.match(/../g)!, byte => Number.parseInt(byte, 16));
  return crypto.subtle.verify("HMAC", await key(secret), bytes, new TextEncoder().encode(text));
}

const hex = (bytes: ArrayBuffer) => Array.from(new Uint8Array(bytes), byte => byte.toString(16).padStart(2, "0")).join("");
export async function createPairingKey() {
  const keys = await crypto.subtle.generateKey({ name: "ECDH", namedCurve: "P-256" }, false, ["deriveBits"]);
  return { privateKey: keys.privateKey, publicKey: hex(await crypto.subtle.exportKey("raw", keys.publicKey)) };
}
export async function pairingCommitment(publicKey: string, nonce: string): Promise<string> {
  if (!/^04[a-f0-9]{128}$/.test(publicKey) || !/^[a-f0-9]{64}$/.test(nonce)) throw new Error("Invalid pairing key.");
  return hex(await crypto.subtle.digest("SHA-256", new TextEncoder().encode(`workbench-pairing-commit-v1\n${publicKey}\n${nonce}`)));
}
export async function derivePairingSecret(privateKey: CryptoKey, publicKey: string): Promise<string> {
  if (!/^04[a-f0-9]{128}$/.test(publicKey)) throw new Error("Invalid pairing key.");
  const raw = Uint8Array.from(publicKey.match(/../g)!, byte => Number.parseInt(byte, 16));
  const remote = await crypto.subtle.importKey("raw", raw, { name: "ECDH", namedCurve: "P-256" }, false, []);
  return hex(await crypto.subtle.deriveBits({ name: "ECDH", public: remote }, privateKey, 256));
}
export function pairingTranscript(port: number, origin: string, clientKey: string, clientNonce: string, serverKey: string, serverNonce: string): string {
  return `workbench-panel-pairing-v1\n${port}\n${origin}\n${clientKey}\n${clientNonce}\n${serverKey}\n${serverNonce}`;
}
export async function comparisonCode(secret: string, transcript: string): Promise<string> {
  const proof = await pairingProof(secret, `comparison\n${transcript}`);
  const digits = String(Number.parseInt(proof.slice(0, 8), 16) % 100000000).padStart(8, "0");
  return `${digits.slice(0, 4)} ${digits.slice(4)}`;
}
