export const AGENT_READ_CONTRACT_RESOURCE_URI = "workbench://agent/read-contract";

/** Bounded static contract and workflow text, intentionally independent of a Panel Session. */
export const AGENT_READ_GUIDANCE = `# Lightstreamer Workbench agent read contract

Use the tools against one deliberate Panel Session. First call list_panel_sessions, choose the exact inspected tab, then call get_status and check readContract.version and capabilities. Ask the user which tab when the target is ambiguous. A connected panel does not prove the page is ready or that an application event will occur.

Find exact targets with search_scope; pass the returned scopeId to summarize_evidence, query_evidence, or search_evidence. Reads use the panel's retained Evidence and do not change the human's selection. Read coverage, evaluation, the readPoint and explicit omissions before interpreting absence. Counts are retained Evidence records, not unique updates or active COMMAND rows. Use query_command_state only with an exact live COMMAND target, item, key, pageEpoch and explicit projection.

For an unfamiliar source, read get_scope.readContext for mode, source identities, item and declared fields independently of injection availability. Follow schema.nextOffset with fieldOffset to read further names; named server schemas are not resolved field lists. Profile observed types with describe_stream, then inspect selected fields from its exact example identities. Use fieldPredicates for AND-combined exact declared fields, with explicit typed ranges and opt-in number-string conversion; nested JSON paths are unsupported. Use summarize_evidence for retained counts/facets, aggregate_evidence for explicit Evidence-record or Logical Update units, and COMMAND projection tools for live derived rows. Reuse a readPoint as at when comparing facts. Resolve business field/model meaning from application code or a guide; ask a focused user question only if a material mapping, entity, unit or time/projection choice remains unknown.

Keep reads scoped and bounded. Results default to 8192 serialized MCP bytes; maxBytes is bounded at 65536. Use limit and selected fields to fit useful pages. Oversized get_evidence and describe_stream reads report measured bytes and a bounded retry budget when possible; otherwise select fewer fields or narrow the Scope. NO_SHAREABLE_EXCERPT means no excerpt in the returned representation; it does not establish redaction or a person's identity. Continue an opaque cursor using only panelSessionId and cursor; its options and read boundary are frozen. For expensive projections, set workBudget only when its bounded default is insufficient; projection reads, payload hydration and elapsed work each have an independent cap.

For local reproduction, ground a candidate in exact retained Evidence or a live supported Scope, validate and prepare it, then review the visible Draft in Workbench. Local Injection is separate from Capture. Execution occurs only through an explicit execution call and application listeners may run; it does not prove server behavior. Preserve each requestId and inspect its existing receipt after an error or lost reply. Never retry an uncertain effect with a new requestId. Server Injection sends a Client Message through the inspected client's normal sendMessage path; it does not inject an inbound server update. An agent may prepare a Server Injection, but only a separate visible human click can approve the exact current Client, Session, message and options. No Local Injection grant implies Server Injection approval. Application-supported attribution metadata is required to link a later Server Update to that message.

For an Evidence-based Local Injection, prepare without a replacement document first. Edit the returned complete expanded Draft, preserving all documentContract.requiredFields and mirroring the COMMAND command/key fields listed in documentContract. Encoded JSON fields are objects or arrays in the editor and become strings at delivery. An unavailable get_scope target supplies recovery queries; it does not prove that no captured update can be prepared. Resolve application-specific key suffixes and payload rules from the application's code or guide, and check the same inspected tab after delivery.

This resource contains static guidance only. It does not expose live Evidence, grant access, wake a host or promise application behavior. Read agent/READS.md in the installed package for the extended contract.`;

export const AGENT_MCP_INITIALIZATION_INSTRUCTIONS = "Start with list_panel_sessions, select the exact inspected tab, then check get_status.readContract and capabilities. Discover scopes and get_scope.readContext before querying unfamiliar fields; describe_stream profiles observed types. Use summaries for retained counts, aggregate_evidence for explicit Logical Update units, fieldPredicates for exact declared fields (no nested JSON paths), and COMMAND tools for derived rows. Resolve missing business meaning from application context or a focused question. Prefer selected fields and inspect coverage/omissions; NO_SHAREABLE_EXCERPT does not establish redaction or identity. For reproduction, prepare from exact Evidence without document for a complete expanded template and preserve its fields. Inspect the same requestId after uncertain outcomes and verify application behavior separately. Read workbench://agent/read-contract or the installed lightstreamer-workbench skill for the workflow.";

export function investigationPrompt(question?: string) {
  const subject = question?.trim() ? question.trim().slice(0, 2000) : "the user's Lightstreamer investigation question";
  return `Investigate ${subject} using Lightstreamer Workbench. Select the intended Panel Session explicitly and inspect its status/capabilities first. Discover exact scopes and get_scope.readContext, profile observed field types, and resolve application meaning before forming predicates. Ask only for material entity, field/model meaning, count unit or time/projection choices that discovery cannot resolve. Choose summaries, typed field examples, explicit Logical Update aggregates or COMMAND projections to match the question; keep reads bounded and align related facts at a readPoint. Inspect coverage, value certainty and omissions before making claims. If an authorized local reproduction would help, validate and prepare a source-grounded candidate and review its complete visible Draft before execution. Inspect existing receipts by requestId after uncertain outcomes; never repeat delivery with a new id. State what Evidence supports and what remains unknown. Verify DOM, application or server behavior separately, and do not claim that a host will wake or resume automatically.`;
}
